apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-svc
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: flask-webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30343